spring:
  elasticsearch:
    rest:
      uris: http://localhost:32934
#      password: "password"
#      username: "username"

management:
  endpoints:
    web:
      exposure:
        include: '*'
#http://localhost:8080/actuator/metrics