spring:
  application:
    name: pipeline-service
    namespace: ${NAMESPACE:seko0716-14-11-28}
  h2:
    console:
      enabled: true
      path: /h2-console
  #      jdbc:h2:mem:testdb
  #      sa
  elasticsearch:
    rest:
      uris: http://localhost:32943
    #      password: "password"
    #      username: "username"
  quartz:
    auto-startup: true
    wait-for-jobs-to-complete-on-shutdown: true
    scheduler-name: namespase-joun
    job-store-type: memory
    properties:
      org.quartz.threadPool:
        threadCount: 2
  profiles:
    active: testcontainers

management:
  endpoints:
    web:
      exposure:
        include: '*'
#http://localhost:8080/actuator/metrics